version: '3.8'
services:
  app:
    build: .
    container_name: ai-resume-scanner
    ports:
      - "8502:8502"
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8502
    volumes:
      - ./:/app
      - ./data:/app/data
    command: ["python", "-m", "streamlit", "run", "app.py", "--server.port", "8502", "--server.address", "0.0.0.0"]
