[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false

[theme]
base = "dark"
primaryColor = "#4ea1f7"
backgroundColor = "#0b1220"
secondaryBackgroundColor = "#0f172a"
textColor = "#e5e7eb"
font = "sans serif"
